//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fotootof.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    public sealed partial class Controls : global::System.Configuration.ApplicationSettingsBase {
        
        private static Controls defaultInstance = ((Controls)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Controls())));
        
        public static Controls Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MainMenuMenuItemDisplayLogsIsChecked {
            get {
                return ((bool)(this["MainMenuMenuItemDisplayLogsIsChecked"]));
            }
            set {
                this["MainMenuMenuItemDisplayLogsIsChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public int MainWindowRowGridLogs {
            get {
                return ((int)(this["MainWindowRowGridLogs"]));
            }
            set {
                this["MainWindowRowGridLogs"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public int MainWindowRowGridLogsDefault {
            get {
                return ((int)(this["MainWindowRowGridLogsDefault"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MainMenuMenuItemDisplayLogsIsCheckedDefault {
            get {
                return ((bool)(this["MainMenuMenuItemDisplayLogsIsCheckedDefault"]));
            }
        }
    }
}
