//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fotootof.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    public sealed partial class Sections : global::System.Configuration.ApplicationSettingsBase {
        
        private static Sections defaultInstance = ((Sections)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Sections())));
        
        public static Sections Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ServerLayout_ShowAllAlbums {
            get {
                return ((bool)(this["ServerLayout_ShowAllAlbums"]));
            }
            set {
                this["ServerLayout_ShowAllAlbums"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ServerLayout_ShowAllAlbumsDefault {
            get {
                return ((bool)(this["ServerLayout_ShowAllAlbumsDefault"]));
            }
        }
    }
}
