//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fotootof.Libraries.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Logs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Logs() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fotootof.Libraries.Properties.Logs", typeof(Logs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sending ListAlbums command to server done !.
        /// </summary>
        public static string SendingAlbumsCommandDone {
            get {
                return ResourceManager.GetString("SendingAlbumsCommandDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sending Authentication command to server done !.
        /// </summary>
        public static string SendingAuthenticationCommandDone {
            get {
                return ResourceManager.GetString("SendingAuthenticationCommandDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sending Authentication command : failed exception !.
        /// </summary>
        public static string SendingAuthenticationCommandException {
            get {
                return ResourceManager.GetString("SendingAuthenticationCommandException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sending Authentication command : failed from server !.
        /// </summary>
        public static string SendingAuthenticationCommandResponseFailed {
            get {
                return ResourceManager.GetString("SendingAuthenticationCommandResponseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sending Authentication command : success !.
        /// </summary>
        public static string SendingAuthenticationCommandResponseOk {
            get {
                return ResourceManager.GetString("SendingAuthenticationCommandResponseOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sending Authentication command : user unauthorized !.
        /// </summary>
        public static string SendingAuthenticationCommandResponseUnauthorized {
            get {
                return ResourceManager.GetString("SendingAuthenticationCommandResponseUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sending {0} command to server {1}:{2} =&gt; Please wait....
        /// </summary>
        public static string SendingClientCommand {
            get {
                return ResourceManager.GetString("SendingClientCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sending {0} command to server {1}:{2} =&gt; Done !.
        /// </summary>
        public static string SendingClientCommandDone {
            get {
                return ResourceManager.GetString("SendingClientCommandDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sending ListSections command to server done !.
        /// </summary>
        public static string SendingListSectionsCommandDone {
            get {
                return ResourceManager.GetString("SendingListSectionsCommandDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sending ListSections command : failed exception !.
        /// </summary>
        public static string SendingListSectionsCommandException {
            get {
                return ResourceManager.GetString("SendingListSectionsCommandException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Envoi de la commande ListSections : échec depuis le serveur !.
        /// </summary>
        public static string SendingListSectionsCommandResponseFailed {
            get {
                return ResourceManager.GetString("SendingListSectionsCommandResponseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Envoi de la commande ListSections : succés !.
        /// </summary>
        public static string SendingListSectionsCommandResponseOk {
            get {
                return ResourceManager.GetString("SendingListSectionsCommandResponseOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Envoi de la commande ListSections : user unauthorized !.
        /// </summary>
        public static string SendingListSectionsCommandUnauthorized {
            get {
                return ResourceManager.GetString("SendingListSectionsCommandUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Envoi de la commande Ping au serveur fin !.
        /// </summary>
        public static string SendingPingCommandDone {
            get {
                return ResourceManager.GetString("SendingPingCommandDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Envoi de la commande Ping : échec exception !.
        /// </summary>
        public static string SendingPingCommandException {
            get {
                return ResourceManager.GetString("SendingPingCommandException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Envoi de la commande Ping : échec depuis le serveur !.
        /// </summary>
        public static string SendingPingCommandResponseFailed {
            get {
                return ResourceManager.GetString("SendingPingCommandResponseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Envoi de la commande Ping : succès !.
        /// </summary>
        public static string SendingPingCommandResponseOk {
            get {
                return ResourceManager.GetString("SendingPingCommandResponseOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Server started..
        /// </summary>
        public static string ServerStarted {
            get {
                return ResourceManager.GetString("ServerStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Server stopped..
        /// </summary>
        public static string ServerStopped {
            get {
                return ResourceManager.GetString("ServerStopped", resourceCulture);
            }
        }
    }
}
