//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fotootof.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fotootof.Properties.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _About XtrmAddons FotootoF.
        /// </summary>
        public static string _About {
            get {
                return ResourceManager.GetString("_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add _Album.
        /// </summary>
        public static string _AddNewAlbum {
            get {
                return ResourceManager.GetString("_AddNewAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add _Section.
        /// </summary>
        public static string _AddNewSection {
            get {
                return ResourceManager.GetString("_AddNewSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Add to Firewall.
        /// </summary>
        public static string _AddToFirewall {
            get {
                return ResourceManager.GetString("_AddToFirewall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Albums.
        /// </summary>
        public static string _Albums {
            get {
                return ResourceManager.GetString("_Albums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _List of Albums.
        /// </summary>
        public static string _AlbumsList {
            get {
                return ResourceManager.GetString("_AlbumsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Add new Album.
        /// </summary>
        public static string _AlbumsNew {
            get {
                return ResourceManager.GetString("_AlbumsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A_uto start.
        /// </summary>
        public static string _AutoStart {
            get {
                return ResourceManager.GetString("_AutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Cancel.
        /// </summary>
        public static string _Cancel {
            get {
                return ResourceManager.GetString("_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Catalog.
        /// </summary>
        public static string _Catalog {
            get {
                return ResourceManager.GetString("_Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Categories.
        /// </summary>
        public static string _Categories {
            get {
                return ResourceManager.GetString("_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _List of Categories.
        /// </summary>
        public static string _CategoriesList {
            get {
                return ResourceManager.GetString("_CategoriesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Add new Categories.
        /// </summary>
        public static string _CategoriesNew {
            get {
                return ResourceManager.GetString("_CategoriesNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Client.
        /// </summary>
        public static string _Client {
            get {
                return ResourceManager.GetString("_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New Client.
        /// </summary>
        public static string _ClientNew {
            get {
                return ResourceManager.GetString("_ClientNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Display.
        /// </summary>
        public static string _Display {
            get {
                return ResourceManager.GetString("_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Edit.
        /// </summary>
        public static string _Edit {
            get {
                return ResourceManager.GetString("_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edition.
        /// </summary>
        public static string _Edition {
            get {
                return ResourceManager.GetString("_Edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à English.
        /// </summary>
        public static string _English {
            get {
                return ResourceManager.GetString("_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Exit.
        /// </summary>
        public static string _Exit {
            get {
                return ResourceManager.GetString("_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _File.
        /// </summary>
        public static string _File {
            get {
                return ResourceManager.GetString("_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Folders.
        /// </summary>
        public static string _Folders {
            get {
                return ResourceManager.GetString("_Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _List of Folders.
        /// </summary>
        public static string _FoldersList {
            get {
                return ResourceManager.GetString("_FoldersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Add new Folder.
        /// </summary>
        public static string _FoldersNew {
            get {
                return ResourceManager.GetString("_FoldersNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à French.
        /// </summary>
        public static string _French {
            get {
                return ResourceManager.GetString("_French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Help.
        /// </summary>
        public static string _Help {
            get {
                return ResourceManager.GetString("_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Language.
        /// </summary>
        public static string _Language {
            get {
                return ResourceManager.GetString("_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logs Window.
        /// </summary>
        public static string _LogsWindow {
            get {
                return ResourceManager.GetString("_LogsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _No.
        /// </summary>
        public static string _No {
            get {
                return ResourceManager.GetString("_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Ok.
        /// </summary>
        public static string _Ok {
            get {
                return ResourceManager.GetString("_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Plugin.
        /// </summary>
        public static string _Plugin {
            get {
                return ResourceManager.GetString("_Plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preferences.
        /// </summary>
        public static string _Preferences {
            get {
                return ResourceManager.GetString("_Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove From _Firewall.
        /// </summary>
        public static string _RemoveFromFirewall {
            get {
                return ResourceManager.GetString("_RemoveFromFirewall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Restart.
        /// </summary>
        public static string _Restart {
            get {
                return ResourceManager.GetString("_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sections.
        /// </summary>
        public static string _Sections {
            get {
                return ResourceManager.GetString("_Sections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Server.
        /// </summary>
        public static string _Server {
            get {
                return ResourceManager.GetString("_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Remote access....
        /// </summary>
        public static string _ServerRemote {
            get {
                return ResourceManager.GetString("_ServerRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Server settings.
        /// </summary>
        public static string _ServerSettings {
            get {
                return ResourceManager.GetString("_ServerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Settings.
        /// </summary>
        public static string _Settings {
            get {
                return ResourceManager.GetString("_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Start.
        /// </summary>
        public static string _Start {
            get {
                return ResourceManager.GetString("_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Stop.
        /// </summary>
        public static string _Stop {
            get {
                return ResourceManager.GetString("_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Theme.
        /// </summary>
        public static string _Theme {
            get {
                return ResourceManager.GetString("_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Dark.
        /// </summary>
        public static string _ThemeDark {
            get {
                return ResourceManager.GetString("_ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Light.
        /// </summary>
        public static string _ThemeLight {
            get {
                return ResourceManager.GetString("_ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _User.
        /// </summary>
        public static string _User {
            get {
                return ResourceManager.GetString("_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Users.
        /// </summary>
        public static string _Users {
            get {
                return ResourceManager.GetString("_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _List of Users.
        /// </summary>
        public static string _UsersList {
            get {
                return ResourceManager.GetString("_UsersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Add new User.
        /// </summary>
        public static string _UsersNew {
            get {
                return ResourceManager.GetString("_UsersNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Windows.
        /// </summary>
        public static string _Windows {
            get {
                return ResourceManager.GetString("_Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Yes.
        /// </summary>
        public static string _Yes {
            get {
                return ResourceManager.GetString("_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à XtrmAddons Fotootof.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start the Http server. Allow incoming Http request to application..
        /// </summary>
        public static string MenuItemTooltip_ServerStart {
            get {
                return ResourceManager.GetString("MenuItemTooltip_ServerStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stop the Http server. Prevent incoming Http request to application..
        /// </summary>
        public static string MenuItemTooltip_ServerStop {
            get {
                return ResourceManager.GetString("MenuItemTooltip_ServerStop", resourceCulture);
            }
        }
    }
}
