//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XtrmAddons.Fotootof.Culture.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesLogs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesLogs() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XtrmAddons.Fotootof.Culture.Properties.ResourcesLogs", typeof(ResourcesLogs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adding application to system tray. Done !.
        /// </summary>
        public static string AddingApplicationToSystemTrayDone {
            get {
                return ResourceManager.GetString("AddingApplicationToSystemTrayDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Application closed..
        /// </summary>
        public static string ApplicationClosed {
            get {
                return ResourceManager.GetString("ApplicationClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Application settings saved..
        /// </summary>
        public static string ApplicationSettingsSaved {
            get {
                return ResourceManager.GetString("ApplicationSettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copying program files to My Documents user folder. Please wait....
        /// </summary>
        public static string CopyingProgramFiles {
            get {
                return ResourceManager.GetString("CopyingProgramFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deleting the application options and parameters. Please wait....
        /// </summary>
        public static string DeletingOptionsWaiting {
            get {
                return ResourceManager.GetString("DeletingOptionsWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deleting the user&apos;s options and parameters. Please wait....
        /// </summary>
        public static string DeletingUserOptionsWaiting {
            get {
                return ResourceManager.GetString("DeletingUserOptionsWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Initializing application window component. Done !.
        /// </summary>
        public static string InitializingApplicationWindowComponentDone {
            get {
                return ResourceManager.GetString("InitializingApplicationWindowComponentDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} deleted !.
        /// </summary>
        public static string ItemDeleted {
            get {
                return ResourceManager.GetString("ItemDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please wait....
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saving the application options &amp; parameters before exit. Please wait....
        /// </summary>
        public static string SavingApplicationWaiting {
            get {
                return ResourceManager.GetString("SavingApplicationWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sending ListAlbums command to server {0}:{1}.
        /// </summary>
        public static string SendingAlbumsCommand {
            get {
                return ResourceManager.GetString("SendingAlbumsCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sending ListAlbums command to server done !.
        /// </summary>
        public static string SendingAlbumsCommandDone {
            get {
                return ResourceManager.GetString("SendingAlbumsCommandDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sending Authentication command to server {0}:{1}.
        /// </summary>
        public static string SendingAuthenticationCommand {
            get {
                return ResourceManager.GetString("SendingAuthenticationCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sending Authentication command to server done !.
        /// </summary>
        public static string SendingAuthenticationCommandDone {
            get {
                return ResourceManager.GetString("SendingAuthenticationCommandDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sending Authentication command : failed exception !.
        /// </summary>
        public static string SendingAuthenticationCommandException {
            get {
                return ResourceManager.GetString("SendingAuthenticationCommandException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sending Authentication command : failed from server !.
        /// </summary>
        public static string SendingAuthenticationCommandResponseFailed {
            get {
                return ResourceManager.GetString("SendingAuthenticationCommandResponseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sending Authentication command : success !.
        /// </summary>
        public static string SendingAuthenticationCommandResponseOk {
            get {
                return ResourceManager.GetString("SendingAuthenticationCommandResponseOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sending Authentication command : user unauthorized !.
        /// </summary>
        public static string SendingAuthenticationCommandUnauthorized {
            get {
                return ResourceManager.GetString("SendingAuthenticationCommandUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sending ListSections command to server {0}:{1}.
        /// </summary>
        public static string SendingListSectionsCommand {
            get {
                return ResourceManager.GetString("SendingListSectionsCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sending ListSections command to server done !.
        /// </summary>
        public static string SendingListSectionsCommandDone {
            get {
                return ResourceManager.GetString("SendingListSectionsCommandDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sending ListSections command : failed exception !.
        /// </summary>
        public static string SendingListSectionsCommandException {
            get {
                return ResourceManager.GetString("SendingListSectionsCommandException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sending ListSections command : failed from server !.
        /// </summary>
        public static string SendingListSectionsCommandResponseFailed {
            get {
                return ResourceManager.GetString("SendingListSectionsCommandResponseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sending ListSections command : success !.
        /// </summary>
        public static string SendingListSectionsCommandResponseOk {
            get {
                return ResourceManager.GetString("SendingListSectionsCommandResponseOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sending ListSections command : user unauthorized !.
        /// </summary>
        public static string SendingListSectionsCommandUnauthorized {
            get {
                return ResourceManager.GetString("SendingListSectionsCommandUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sending Ping command to server {0}:{1}.
        /// </summary>
        public static string SendingPingCommand {
            get {
                return ResourceManager.GetString("SendingPingCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sending Ping command to server done !.
        /// </summary>
        public static string SendingPingCommandDone {
            get {
                return ResourceManager.GetString("SendingPingCommandDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sending Ping command : failed exception !.
        /// </summary>
        public static string SendingPingCommandException {
            get {
                return ResourceManager.GetString("SendingPingCommandException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sending Ping command : failed from server !.
        /// </summary>
        public static string SendingPingCommandResponseFailed {
            get {
                return ResourceManager.GetString("SendingPingCommandResponseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sending Ping command : success !.
        /// </summary>
        public static string SendingPingCommandResponseOk {
            get {
                return ResourceManager.GetString("SendingPingCommandResponseOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Server started..
        /// </summary>
        public static string ServerStarted {
            get {
                return ResourceManager.GetString("ServerStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Server stopped..
        /// </summary>
        public static string ServerStopped {
            get {
                return ResourceManager.GetString("ServerStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Starting the application. Initialiazing the options &amp; parameters. Please wait....
        /// </summary>
        public static string StartingApplicationWaiting {
            get {
                return ResourceManager.GetString("StartingApplicationWaiting", resourceCulture);
            }
        }
    }
}
